global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Platform API
  - job_name: 'platform-api'
    static_configs:
      - targets: ['platform-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Test Tenant API
  - job_name: 'test-tenant-api'
    static_configs:
      - targets: ['test-tenant-api:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL Exporter (if we add it later)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  # Redis Exporter (if we add it later)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s
