# BackSaas API Gateway Configuration
# This file defines routing rules, authentication, rate limiting, and other gateway settings

# Basic gateway settings
port: "8000"
environment: "development"

# Authentication configuration
auth:
  enabled: true
  required: false  # Set to true to require auth for all routes by default
  header_name: "Authorization"
  jwt_secret: ""  # Will be overridden by environment variable
  bypass_paths:
    - "/health"
    - "/metrics"
    - "/api/auth/login"
    - "/api/auth/register"

# Rate limiting configuration
rate_limit:
  enabled: true
  requests_per_minute: 100
  burst_size: 20
  key_strategy: "ip"  # ip, user, tenant, custom
  
  # Different limits for different user types
  limits:
    admin: 
      requests_per_minute: 1000
      burst_size: 100
    premium:
      requests_per_minute: 500
      burst_size: 50
    free:
      requests_per_minute: 60
      burst_size: 10

# CORS configuration
cors:
  enabled: true
  allowed_origins:
    - "http://localhost:3000"
    - "https://*.backsaas.dev"
    - "https://*.backsaas.com"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
    - "PATCH"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Tenant-ID"
    - "X-Request-ID"
  allow_credentials: true
  max_age: 3600

# Monitoring and logging
monitoring:
  enabled: true
  metrics_path: "/metrics"
  health_path: "/health"
  log_level: "info"
  log_format: "json"
  log_requests: true
  tracing_enabled: false

# Route definitions
routes:
  # Platform API (system tenant) - manages tenants, schemas, etc. - MOVED TO TOP FOR PRIORITY
  - description: "Platform Management API"
    path_prefix: "/api/platform"
    backend:
      url: "http://platform-api:8080"
      timeout: "30s"
      max_retries: 3
      health_check_path: "/health"
    auth:
      enabled: false  # Let platform-api handle its own authentication
    rate_limit:
      enabled: true
      requests_per_minute: 200
      burst_size: 50
    enabled: true

  # Health Dashboard API - system health and coverage data
  - description: "System Health Dashboard API"
    path_prefix: "/api/system-health"
    backend:
      url: "http://health-dashboard:8090"
      timeout: "30s"
      max_retries: 3
      health_check_path: "/api/status"
    transform:
      strip_prefix: true  # Strip the path_prefix before forwarding
      add_headers:
        X-Interface-Type: "system-health"
    auth:
      enabled: false  # Temporarily disabled for testing
    rate_limit:
      enabled: true
      requests_per_minute: 100
      burst_size: 20
    enabled: true

  # Admin Console UI - platform management interface (host-based)
  - description: "Admin Console UI (Host-based)"
    host: "admin.backsaas.dev"
    path_prefix: "/"
    backend:
      url: "http://admin-console:3000"
      timeout: "30s"
      max_retries: 2
      health_check_path: "/"
    auth:
      enabled: false  # Let admin console handle its own auth
    rate_limit:
      enabled: true
      requests_per_minute: 300
      burst_size: 60
    transform:
      add_headers:
        X-Interface-Type: "admin-console"
    enabled: true

  # Admin Console - all /admin traffic forwarded as-is to Next.js with basePath
  - description: "Admin Console (All /admin traffic)"
    path_prefix: "/admin"
    backend:
      url: "http://admin-console:3000"
      timeout: "30s"
      max_retries: 2
      health_check_path: "/admin"
    auth:
      enabled: false  # Let admin console handle its own auth
    rate_limit:
      enabled: true
      requests_per_minute: 300
      burst_size: 60
    transform:
      add_headers:
        X-Interface-Type: "admin-console"
      # No strip_prefix - Next.js basePath handles /admin prefix
    enabled: true

  # Health Dashboard - system monitoring interface
  - description: "Health Dashboard"
    path_prefix: "/dashboard"
    backend:
      url: "http://health-dashboard:8090"
      timeout: "30s"
      max_retries: 2
      health_check_path: "/health"
    auth:
      enabled: false  # Public access for now
    rate_limit:
      enabled: true
      requests_per_minute: 100
      burst_size: 20
    transform:
      add_headers:
        X-Interface-Type: "health-dashboard"
      rewrite_path: "/"  # Remove /dashboard prefix when forwarding to backend
    enabled: true

  # Tenant UI - business interface (disabled - service not implemented yet)
  - description: "Tenant UI"
    host: "*.backsaas.dev"
    path_prefix: "/"
    backend:
      url: "http://tenant-ui:3001"
      timeout: "30s"
      max_retries: 2
      health_check_path: "/api/health"
    auth:
      enabled: true
      required: true
    rate_limit:
      enabled: true
      requests_per_minute: 500
      burst_size: 100
    transform:
      add_headers:
        X-Interface-Type: "tenant-ui"
    enabled: false

  # Tenant UI (path-based routing alternative) (disabled - service not implemented yet)
  - description: "Tenant UI Path-based"
    path_prefix: "/app"
    backend:
      url: "http://tenant-ui:3001"
      timeout: "30s"
      max_retries: 2
      health_check_path: "/api/health"
    auth:
      enabled: true
      required: true
    rate_limit:
      enabled: true
      requests_per_minute: 500
      burst_size: 100
    transform:
      add_headers:
        X-Interface-Type: "tenant-ui"
      rewrite_path: "/"
    enabled: false


  # Tenant API routing by subdomain (disabled - using existing test-tenant-api service)
  - description: "Tenant API by Subdomain"
    host: "*.api.backsaas.dev"
    path_prefix: "/"
    backend:
      url: "http://test-tenant-api:8081"  # Tenant API service
      timeout: "30s"
      max_retries: 3
      health_check_path: "/health"
    transform:
      add_headers:
        X-Gateway-Route: "tenant-api-subdomain"
    auth:
      enabled: true
      required: true
    rate_limit:
      enabled: true
      requests_per_minute: 300
      burst_size: 60
    enabled: false

  # Tenant API routing by path (disabled - using existing test-tenant-api service)
  - description: "Tenant API by Path"
    path_prefix: "/api/tenants/"
    backend:
      url: "http://test-tenant-api:8081"
      timeout: "30s"
      max_retries: 3
      health_check_path: "/health"
    transform:
      add_headers:
        X-Gateway-Route: "tenant-api-path"
    auth:
      enabled: true
      required: true
    rate_limit:
      enabled: true
      requests_per_minute: 300
      burst_size: 60
    enabled: false

  # Authentication service (disabled - service not implemented yet)
  - description: "Authentication API"
    path_prefix: "/auth"
    backend:
      url: "http://auth-service:8082"
      timeout: "15s"
      max_retries: 2
      health_check_path: "/health"
    auth:
      enabled: false  # Auth service doesn't need auth
    rate_limit:
      enabled: true
      requests_per_minute: 60
      burst_size: 20
    enabled: false

  # Static assets and documentation (disabled - service not implemented yet)
  - description: "Static Assets"
    path_prefix: "/static"
    backend:
      url: "http://static-service:8083"
      timeout: "10s"
      max_retries: 1
    auth:
      enabled: false
    rate_limit:
      enabled: true
      requests_per_minute: 500
      burst_size: 100
    enabled: false

  # API documentation (disabled - service not implemented yet)
  - description: "API Documentation"
    path_prefix: "/docs"
    backend:
      url: "http://docs-service:8084"
      timeout: "10s"
      max_retries: 1
    auth:
      enabled: false
    rate_limit:
      enabled: true
      requests_per_minute: 100
      burst_size: 20
    enabled: false

  # Webhook endpoints (disabled - service not implemented yet)
  - description: "Webhook Endpoints"
    path_prefix: "/webhooks"
    backend:
      url: "http://webhook-service:8085"
      timeout: "60s"
      max_retries: 1
    auth:
      enabled: true
      required: true
      required_scopes: ["webhook:receive"]
    rate_limit:
      enabled: true
      requests_per_minute: 1000
      burst_size: 200
    transform:
      add_headers:
        X-Gateway-Route: "webhook"
    enabled: false

  # Health check aggregation (disabled - service not implemented yet)
  - description: "Health Check Aggregation"
    path_prefix: "/health/services"
    backend:
      url: "http://health-service:8086"
      timeout: "5s"
      max_retries: 1
    auth:
      enabled: false
    rate_limit:
      enabled: true
      requests_per_minute: 30
      burst_size: 10
    enabled: false
